# -*- coding: utf-8 -*-
"""APP_MATE_CONEXION_FIREBASE .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kEwYmeUJTJyJUPKX_HOHNNrsG8GrLGom
"""

#APP MATE-MÁTICO
#Cargamos las base de datos desde firestone NoSQL, no son tablas estrcitas

from google.colab import auth
auth.authenticate_user()

from google.cloud import firestore

# Conectarse usando tu proyecto actual
db = firestore.Client(project="talento14bd")

# Probar leyendo una colección
docs = db.collection("Usuarios").stream()
for doc in docs:
    print(doc.id, doc.to_dict())

from google.cloud import firestore

db = firestore.Client(project="talento14bd")
colecciones = db.collections()

print("Colecciones encontradas en Firebase:")
for col in colecciones:
    print(f"- {col.id}")

import pandas as pd
from google.colab import files
from google.cloud import firestore

# Inicializar cliente con tu proyecto
db = firestore.Client(project="talento14bd")

# Función para descargar cualquier colección a CSV de forma limpia
def descargar_coleccion_a_csv(nombre_coleccion, nombre_archivo_salida):
    try:
        docs = db.collection(nombre_coleccion).stream()
        lista_datos = []
        for doc in docs:
            data = doc.to_dict()
            data['id_documento'] = doc.id
            lista_datos.append(data)

        if lista_datos:
            df = pd.DataFrame(lista_datos)

            # --- LIMPIEZA DE DATOS PARA EVITAR ERRORES EN SQL SERVER ---
            for col in df.select_dtypes(include=['object']).columns:
                # Convertir todo a string, limpiar espacios extremos y reemplazar saltos de línea internos que rompen filas en CSVs
                df[col] = df[col].astype(str).str.strip()
                df[col] = df[col].replace({'nan': None, 'None': None, 'NaT': None})
                # Reemplazar saltos de línea o retornos de carro dentro de los textos para que no rompan el CSV
                df[col] = df[col].str.replace('\r\n', ' ').str.replace('\n', ' ')

            # Guardar en CSV asegurando UTF-8 y manejo correcto de comillas
            df.to_csv(nombre_archivo_salida, index=False, encoding='latin1', quoting=1, errors='ignore')
            print(f"¡Éxito! Colección '{nombre_coleccion}' guardada y limpiada.")
            files.download(nombre_archivo_salida)
        else:
            print(f"La colección '{nombre_coleccion}' está vacía.")
    except Exception as e:
        print(f"Error en {nombre_coleccion}: {e}")

# Ejecutar para las colecciones principales
descargar_coleccion_a_csv("usuarios", "usuarios.csv")
descargar_coleccion_a_csv("progreso", "progreso.csv")
descargar_coleccion_a_csv("PlantillasEjercicio", "PlantillasEjercicio.csv")
descargar_coleccion_a_csv("modulos", "modulos.csv")

!pip install pyodbc sqlalchemy

import pandas as pd
import sqlite3

# 1. Asegúrate de haber subido tu archivo 'usuarios.csv' al panel izquierdo de Colab
ruta_csv = "usuarios.csv"

# 2. Leer el CSV asegurando que todas las columnas entren como texto (evita truncamientos)
df = pd.read_csv(ruta_csv, encoding='latin1', dtype=str)

# 3. Crear una base de datos SQLite temporal en Colab y guardar la tabla
conexion = sqlite3.connect('base_usuarios.db')
df.to_sql('usuarios', con=conexion, if_exists='replace', index=False)
conexion.close()

print("¡Tabla creada y datos importados con éxito en Colab sin errores!")

# Exportar el DataFrame limpio a un nuevo archivo CSV listo para SQL Server
df.to_csv("usuarios_limpio_para_sql.csv", index=False, encoding='utf-8-sig', quoting=1)

print("¡Archivo 'usuarios_limpio_para_sql.csv' generado con éxito!")

import pandas as pd
from google.colab import files
from google.cloud import firestore

# Inicializar cliente con tu proyecto
db = firestore.Client(project="talento14bd")

# Función para descargar cualquier colección a CSV
def descargar_coleccion_a_csv(nombre_coleccion, nombre_archivo_salida):
    try:
        docs = db.collection(nombre_coleccion).stream()
        lista_datos = []
        for doc in docs:
            data = doc.to_dict()
            data['id_documento'] = doc.id
            lista_datos.append(data)

        if lista_datos:
            df = pd.DataFrame(lista_datos)
            df.to_csv(nombre_archivo_salida, index=False)
            print(f"¡Éxito! Colección '{nombre_coleccion}' guardada.")
            files.download(nombre_archivo_salida)
        else:
            print(f"La colección '{nombre_coleccion}' está vacía.")
    except Exception as e:
        print(f"Error en {nombre_coleccion}: {e}")

# Ejecutar para las colecciones principales
descargar_coleccion_a_csv("usuarios", "usuarios.csv")
descargar_coleccion_a_csv("progreso", "progreso.csv")
descargar_coleccion_a_csv("PlantillasEjercicio", "PlantillasEjercicio.csv")
descargar_coleccion_a_csv("modulos", "modulos.csv")